# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceAllocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Allocation Name', max_length=32)),
                ('notes', models.TextField(blank=True, help_text='optional notes')),
            ],
            options={
                'verbose_name': 'Space Allocation',
            },
        ),
        migrations.CreateModel(
            name='UserProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='a short name for your project', max_length=32)),
                ('active', models.BooleanField(default=True, help_text='whether or not you are active within the space currently')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('projected_completion_date', models.DateField(help_text='when do you think you will finish this project?')),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(help_text='a few words about your project')),
                ('space_requirement', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.SpaceAllocations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Project',
            },
        ),
    ]
