# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='hackerEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='a common name for this piece of equipment', max_length=64, unique=True)),
                ('manufacturer', models.CharField(help_text='the equipment manufacturer', max_length=64)),
                ('equipment_model', models.CharField(help_text='the model for this equipment', max_length=32, verbose_name='model')),
                ('value', models.IntegerField(help_text='fair market value')),
                ('notes', models.TextField(blank=True, help_text='Optional Notes', null=True)),
                ('location', models.ForeignKey(help_text='location of equipment', on_delete=django.db.models.deletion.CASCADE, to='spaces.Locations')),
                ('peramanent_owner', models.ForeignKey(blank=True, help_text='if on loan from someone, who does this belong to permanently?', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
