# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name for the workshop', max_length=32, unique=True)),
                ('number', models.CharField(help_text='number for class. e.g. 101, 500, etc.', max_length=4)),
                ('date', models.DateField(help_text='date workshop will occur')),
                ('start_time', models.TimeField(help_text='workshop start time')),
                ('end_time', models.TimeField(help_text='workshop end time')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('description', models.TextField(help_text='description for your workshop')),
                ('attendees', models.ManyToManyField(help_text='people attending this workshop', related_name='user_attendees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name for this category', max_length=32, unique=True)),
                ('description', models.TextField(blank=True, help_text='optional notes', null=True)),
            ],
            options={
                'verbose_name': 'Workshop Category',
                'verbose_name_plural': 'Workshop Categories',
            },
        ),
        migrations.AddField(
            model_name='workshop',
            name='category',
            field=models.ForeignKey(help_text='category this workshop falls under', on_delete=django.db.models.deletion.CASCADE, to='workshops.WorkshopCategory'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='instructor',
            field=models.ForeignKey(help_text='person presenting the workshop', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
