# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HackerSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the name for your hacker or maker space', max_length=64)),
                ('slogan', models.CharField(blank=True, help_text='an optional slogan to show up on your pages for your hackerspace', max_length=256, null=True)),
                ('logo', models.ImageField(blank=True, height_field='logo_height', help_text='an optional logo for your hackerspace', null=True, upload_to='logos/', width_field='logo_width')),
                ('address1', models.CharField(help_text='the address for your hackerspace', max_length=96)),
                ('address2', models.CharField(blank=True, help_text='2nd optional address line', max_length=96, null=True)),
                ('city', models.CharField(help_text='city', max_length=64)),
                ('state', models.CharField(help_text='state', max_length=2)),
                ('zip_code', models.CharField(help_text='zip/postal code', max_length=16)),
            ],
            options={
                'verbose_name': 'Hacker Space',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the name for this location', max_length=32)),
                ('notes', models.TextField(blank=True, help_text='optional notes', null=True)),
                ('space', models.ForeignKey(help_text='the space this location is associated with', on_delete=django.db.models.deletion.CASCADE, to='spaces.HackerSpace')),
            ],
        ),
    ]
