# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this interest', max_length=32, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Optional Notes', null=True)),
            ],
            options={
                'verbose_name_plural': 'Member Interests',
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsa_key', models.TextField(blank=True, help_text='optional RSA Public Key', null=True)),
                ('pgp_key', models.TextField(blank=True, help_text='optional PGP Key', null=True)),
                ('avatar', models.ImageField(blank=True, help_text='optional avatar (jpg,gif,png)', null=True, upload_to='avatars/')),
                ('hackerspace', models.ForeignKey(blank=True, help_text='the space the member belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='spaces.HackerSpace')),
                ('interests', models.ManyToManyField(blank=True, to='members.MemberInterests')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Profile',
            },
        ),
    ]
