# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='trainingManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name for this manual', max_length=32, unique=True)),
                ('training_time', models.IntegerField(help_text='approximate time in minutes training will take to complete')),
                ('training_docs', models.FileField(blank=True, help_text='optional documentation that can be printed', null=True, upload_to='manuals/')),
                ('notes', models.TextField(blank=True, help_text='optional notes', null=True)),
                ('equipment', models.ForeignKey(help_text='equipment this manual is for', on_delete=django.db.models.deletion.CASCADE, to='equipment.hackerEquipment')),
                ('maintainer', models.ForeignKey(help_text='person who maintains this manual', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
